### ISSUE TITLE
不更新了吗

### ISSUE THREAD

**Issue by Lmzaxx** [yangfei4913438/strapi-provider-upload-qiniu-cloud#2]
// 机房区域配置
const ZoneMap = {
  "Zone_z0": qiniu.zone.Zone_z0,  // 华东
  "Zone_z1": qiniu.zone.Zone_z1,  // 华北
  "Zone_z2": qiniu.zone.Zone_z2,  // 华南
  "Zone_na0": qiniu.zone.Zone_na0, // 北美
  "Zone_cn_east_2": qiniu.zone.Zone_cn_east_2, // 华东2
  "Zone_as0": qiniu.zone.Zone_as0, // 新加坡
  "Zone_ap_northeast_1": qiniu.zone.Zone_ap_northeast_1, // 首尔

**Comment by yangfei4913438** [comment]
你好，不好意思刚看到，我看了一下SDK, 里面确实多了一个区域，我刚才把差的那个区域，补充了一下。

这是SDK里面能看到的。
![image](https://github.com/yangfei4913438/provider-upload-qiniu-cloud/assets/15223848/537741d9-ded4-4239-b796-ba1e1348ce6e)

SDK里面不存在的区域，还是要等SDK更新之后，再同步更新。

如果有问题，可以去官方问问到底啥情况。
